Importing Libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

Libraries imported successfully!

Upload the Excel dataset

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Financial Sample.xlsx to Financial Sample.xlsx

In [3]:
# Get the uploaded filename
file_name = next(iter(uploaded))

# Load Excel file
df = pd.read_excel(file_name)

print("Dataset loaded successfully!")

Dataset loaded successfully!

Datast Shape

In [4]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 700
Columns: 16

Inspection of dataset

In [5]:
# Display first 5 rows
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [6]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        647 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [7]:
# Check missing values
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [8]:
# Statistical summary
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

Clean the Column Names

In [9]:
# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

# Display cleaned column names
print(df.columns.tolist())

['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name', 'Year']

Check the data types

In [10]:
df.dtypes

Segment                        object
Country                        object
Product                        object
Discount Band                  object
Units Sold                    float64
Manufacturing Price             int64
Sale Price                      int64
Gross Sales                   float64
Discounts                     float64
Sales                         float64
COGS                          float64
Profit                        float64
Date                   datetime64[ns]
Month Number                    int64
Month Name                     object
Year                            int64
dtype: object

Date Convertion

In [11]:
df['Date'] = pd.to_datetime(df['Date'])

print(df['Date'].dtype)

datetime64[ns]

Checking numerical columns

In [12]:
numeric_columns = [
    'Units Sold',
    'Manufacturing Price',
    'Sale Price',
    'Gross Sales',
    'Discounts',
    'Sales',
    'COGS',
    'Profit'
]

df[numeric_columns].dtypes

Units Sold             float64
Manufacturing Price      int64
Sale Price               int64
Gross Sales            float64
Discounts              float64
Sales                  float64
COGS                   float64
Profit                 float64
dtype: object

Handle missing values

In [13]:
# Check missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
Sales                   0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

We are filling ***Discount Band*** with ***UnKnown*** because it is categorial

In [14]:
# Fill missing Discount Band values
df['Discount Band'] = df['Discount Band'].fillna('Unknown')

print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
Sales                  0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

Verify duplicates

In [15]:
# Check duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

Final Check

In [16]:
print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (700, 16)

Missing values:
Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
Sales                  0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

Duplicate rows: 0

#EDA

Numerical  Summary

In [17]:
# Statistical summary of numerical columns
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Units Sold,700.0,1608.294286,200.0,905.0,1542.5,2229.125,4492.5,867.427859
Manufacturing Price,700.0,96.477143,3.0,5.0,10.0,250.0,260.0,108.602612
Sale Price,700.0,118.428571,7.0,12.0,20.0,300.0,350.0,136.775515
Gross Sales,700.0,182759.426429,1799.0,17391.75,37980.0,279025.0,1207500.0,254262.284378
Discounts,700.0,13150.354629,0.0,800.32,2585.25,15956.34375,149677.5,22962.928775
Sales,700.0,169609.0718,1655.08,15928.0,35540.2,261077.5,1159200.0,236726.34691
COGS,700.0,145475.211429,918.0,7490.0,22506.25,245607.5,950625.0,203865.506118
Profit,700.0,24133.860371,-40617.5,2805.96,9242.2,22662.0,262200.0,42760.626563
Date,700,2014-04-28 21:36:00,2013-09-01 00:00:00,2013-12-24 06:00:00,2014-05-16 12:00:00,2014-09-08 12:00:00,2014-12-01 00:00:00,NaN
Month Number,700.0,7.9,1.0,5.75,9.0,10.25,12.0,3.377321
Year,700.0,2013.75,2013.0,2013.75,2014.0,2014.0,2014.0,0.433322

Categorical columns

In [18]:
# Unique values in categorical columns
categorical_columns = ['Segment', 'Country', 'Product', 'Discount Band']

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].value_counts())

Segment:
Segment
Government          300
Midmarket           100
Channel Partners    100
Enterprise          100
Small Business      100
Name: count, dtype: int64

Country:
Country
Canada                      140
Germany                     140
France                      140
Mexico                      140
United States of America    140
Name: count, dtype: int64

Product:
Product
Paseo        202
Velo         109
VTT          109
Amarilla      94
Montana       93
Carretera     93
Name: count, dtype: int64

Discount Band:
Discount Band
High       245
Medium     242
Low        160
Unknown     53
Name: count, dtype: int64

Date range

In [19]:
print("Start Date:", df['Date'].min())
print("End Date:", df['Date'].max())

Start Date: 2013-09-01 00:00:00
End Date: 2014-12-01 00:00:00